name: Lint project files

on: 
  pull_request:

jobs:
  eslint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v2
      - uses: actions/setup-node@v3
        with:
          cache: 'pnpm'

      - name: Install Node Dependencies
        run: pnpm i

      - name: Build project
        run: pnpm -r build

      - name: Save Code Linting Report JSON
        run: pnpm lint:report
        continue-on-error: true

      - name: Annotate Code Linting Results
        uses: ataylorme/eslint-annotate-action@1.1.2
        with:
          repo-token: "${{ github.token }}"
          report-json: "eslint.report.json"

      - name: Upload ESLint report
        uses: actions/upload-artifact@v2
        with:
          name: eslint-report.log.json
          path: eslint-report.log.json